coverage:
  precision: 2
  round: down
  range: "91...100"
  status:
    project:
      default:
        target: 91%
        threshold: 0%
    patch:
      default:
        target: 91%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

github_checks:
  annotations: true
